In [1]:
# Pandas basics

In [1]:
from sys import version_info
version_info

sys.version_info(major=2, minor=7, micro=11, releaselevel='final', serial=0)

In [2]:
import numpy as np
import pandas as pd
import warnings; warnings.simplefilter('ignore')

In [3]:
#first steps with dataframe Class
#on the rather fundamental level, the DataFrame class is designed to manage indexed and labeled data

In [42]:
df = pd.DataFrame([10,20,30,40], columns=['numbers'],index=['a','b','c','d'])
df

numbers
a       10
b       20
c       30
d       40

In [43]:
#
#

In [44]:
df.index

Index([u'a', u'b', u'c', u'd'], dtype='object')

In [45]:
df.columns

Index([u'numbers'], dtype='object')

In [46]:
df.ix['c']

numbers    30
Name: c, dtype: int64

In [47]:
df.ix[['a','d]]

SyntaxError: EOL while scanning string literal (<ipython-input-47-0252efa3c0ca>, line 1)

In [48]:
#some important attributes and methods of the class

In [49]:
df.index[1:3]

Index([u'b', u'c'], dtype='object')

In [50]:
df.ix[df.index[1:3]]

numbers
b       20
c       30

In [51]:
df.sum() #per column

numbers    100
dtype: int64

In [52]:
df.apply(lambda x: x**2) # square of every element

numbers
a      100
b      400
c      900
d     1600

In [53]:
#vectorized operations on a DataFrame object generally work as on a NumPy and ndarray object

In [54]:
df ** 2 # again square, this time Numpy-like 

numbers
a      100
b      400
c      900
d     1600

In [55]:
#enlarge the ddataFrame object in both dimensions is possible

In [56]:
df['floats'] = (1.5,2.5,3.5,4.5) # new column is generated
df

numbers  floats
a       10     1.5
b       20     2.5
c       30     3.5
d       40     4.5

In [57]:
df['floats'] #selection of column

a    1.5
b    2.5
c    3.5
d    4.5
Name: floats, dtype: float64

In [58]:
# A whole DataFrame object can also be taken a new column. In such a case, indices are aligned autoamtically

In [59]:
df['names'] = pd.DataFrame(['Yves','Guido','Felix','Francesc'], index=['d','a','b','c'])
df

numbers  floats     names
a       10     1.5     Guido
b       20     2.5     Felix
c       30     3.5  Francesc
d       40     4.5      Yves

In [60]:
#Appending data works similarly- however, note the index replacement

In [61]:
df.append({'numbers':100, 'floats':5.75,'names':'Henry'}, ignore_index=True)
#temporary object; df not changed

numbers  floats     names
0       10    1.50     Guido
1       20    2.50     Felix
2       30    3.50  Francesc
3       40    4.50      Yves
4      100    5.75     Henry

In [62]:
df

numbers  floats     names
a       10     1.5     Guido
b       20     2.5     Felix
c       30     3.5  Francesc
d       40     4.5      Yves

In [63]:
#solution : append a Dataframe object provinf the appropriate index information
df = df.append(pd.DataFrame({'numbers': 100, 'floats': 5.75,'names': 'Henry'}, index=['e',]))
df

floats     names  numbers
a    1.50     Guido       10
b    2.50     Felix       20
c    3.50  Francesc       30
d    4.50      Yves       40
e    5.75     Henry      100

In [64]:
#one of the strengths of pandas is working with missing data


In [ ]:
df.join(pd.DataFrame([1,4,9,16,25], index=['a','b','c','d','y'], columns=['squares',]))
#temporary object; default inner join based on index

In [65]:
#Doing an Outer join

df = df.join(pd.DataFrame([1,4,9,16,25], index=['a','b','c','d','y'], columns=['squares',]), how='outer')
df

floats     names  numbers  squares
a    1.50     Guido     10.0      1.0
b    2.50     Felix     20.0      4.0
c    3.50  Francesc     30.0      9.0
d    4.50      Yves     40.0     16.0
e    5.75     Henry    100.0      NaN
y     NaN       NaN      NaN     25.0

In [67]:
#Join methods are inner, outer, left, right

In [68]:
#Although there are missing values, the majority of method calls will still work

In [69]:
df[['numbers','squares']].mean()

numbers    40.0
squares    11.0
dtype: float64

In [70]:
df[['numbers','squares']].std()

numbers    35.355339
squares     9.669540
dtype: float64

In [73]:
dfs = pd.DataFrame([1,1,1,2,np.nan])

In [74]:
dfs

0
0  1.0
1  1.0
2  1.0
3  2.0
4  NaN

In [75]:
dfs.mean() # 5th value is ignored while calculating mean

0    1.25
dtype: float64

In [71]:
#Second Steps with DataFrame Class

In [72]:
#First , a set of random dummy data as a ndarray object

In [76]:
a = np.random.standard_normal((9,4))
a.round(6)

array([[-0.424572, -1.611881, -0.821341, -0.775389],
       [-0.722853,  0.536708,  0.777658, -0.860132],
       [-1.450042, -0.905503,  1.140549,  0.367753],
       [-2.123858, -0.337876, -0.102133,  2.083287],
       [-0.445971,  0.554735, -1.675331, -0.140789],
       [ 0.582838,  0.404033, -2.244998, -0.374251],
       [ 1.375021,  1.552821, -0.194917,  1.428712],
       [-0.204587,  0.39103 , -1.304569, -0.645882],
       [-1.601548,  0.67791 ,  0.621679,  0.905617]])

In [77]:
#this can be used to insantiate a DataFrame object

In [78]:
df = pd.DataFrame(a)
df

0         1         2         3
0 -0.424572 -1.611881 -0.821341 -0.775389
1 -0.722853  0.536708  0.777658 -0.860132
2 -1.450042 -0.905503  1.140549  0.367753
3 -2.123858 -0.337876 -0.102133  2.083287
4 -0.445971  0.554735 -1.675331 -0.140789
5  0.582838  0.404033 -2.244998 -0.374251
6  1.375021  1.552821 -0.194917  1.428712
7 -0.204587  0.391030 -1.304569 -0.645882
8 -1.601548  0.677910  0.621679  0.905617

In [79]:
#adding column names...

In [81]:
df.columns = ['No1','No2','No3','No4']
df

No1       No2       No3       No4
0 -0.424572 -1.611881 -0.821341 -0.775389
1 -0.722853  0.536708  0.777658 -0.860132
2 -1.450042 -0.905503  1.140549  0.367753
3 -2.123858 -0.337876 -0.102133  2.083287
4 -0.445971  0.554735 -1.675331 -0.140789
5  0.582838  0.404033 -2.244998 -0.374251
6  1.375021  1.552821 -0.194917  1.428712
7 -0.204587  0.391030 -1.304569 -0.645882
8 -1.601548  0.677910  0.621679  0.905617

In [82]:
df['No2'][3]

-0.33787560353888701

In [ ]:
#adding a DatetimeIndex

In [83]:
dates = pd.date_range('2015-1-1', periods=9, freq='M') # try freq='MS'
dates

DatetimeIndex(['2015-01-31', '2015-02-28', '2015-03-31', '2015-04-30',
               '2015-05-31', '2015-06-30', '2015-07-31', '2015-08-31',
               '2015-09-30'],
              dtype='datetime64[ns]', freq='M')

In [84]:
df.index= dates
df 

No1       No2       No3       No4
2015-01-31 -0.424572 -1.611881 -0.821341 -0.775389
2015-02-28 -0.722853  0.536708  0.777658 -0.860132
2015-03-31 -1.450042 -0.905503  1.140549  0.367753
2015-04-30 -2.123858 -0.337876 -0.102133  2.083287
2015-05-31 -0.445971  0.554735 -1.675331 -0.140789
2015-06-30  0.582838  0.404033 -2.244998 -0.374251
2015-07-31  1.375021  1.552821 -0.194917  1.428712
2015-08-31 -0.204587  0.391030 -1.304569 -0.645882
2015-09-30 -1.601548  0.677910  0.621679  0.905617

In [85]:
#Closing the circle: from DataFrame object to ndarray object

In [86]:
np.array(df).round(6)

array([[-0.424572, -1.611881, -0.821341, -0.775389],
       [-0.722853,  0.536708,  0.777658, -0.860132],
       [-1.450042, -0.905503,  1.140549,  0.367753],
       [-2.123858, -0.337876, -0.102133,  2.083287],
       [-0.445971,  0.554735, -1.675331, -0.140789],
       [ 0.582838,  0.404033, -2.244998, -0.374251],
       [ 1.375021,  1.552821, -0.194917,  1.428712],
       [-0.204587,  0.39103 , -1.304569, -0.645882],
       [-1.601548,  0.67791 ,  0.621679,  0.905617]])

In [87]:
df.values

array([[-0.4245722 , -1.61188101, -0.82134096, -0.77538891],
       [-0.72285252,  0.53670782,  0.77765783, -0.8601318 ],
       [-1.45004198, -0.90550332,  1.14054874,  0.36775328],
       [-2.1238584 , -0.3378756 , -0.10213298,  2.0832868 ],
       [-0.44597057,  0.55473501, -1.67533107, -0.14078878],
       [ 0.58283793,  0.4040326 , -2.24499793, -0.37425079],
       [ 1.37502088,  1.55282075, -0.19491652,  1.42871213],
       [-0.20458708,  0.39102987, -1.30456943, -0.64588208],
       [-1.6015477 ,  0.67791042,  0.62167928,  0.90561737]])

In [88]:
#Basic Analytics

In [89]:
#The DataFrame class has many conveneince methods already built in (I)

In [90]:
df.sum()

No1   -5.015572
No2    1.261977
No3   -3.803403
No4    1.988927
dtype: float64

In [91]:
a.sum(axis=0)

array([-5.01557165,  1.26197653, -3.80340303,  1.98892722])

In [93]:
a.sum(axis=1)    

array([-3.63318307, -0.26861867, -0.84724328, -0.48058018, -1.70735541,
       -1.63237818,  4.16163723, -1.76400873,  0.60365937])

In [94]:
df.mean()

No1   -0.557286
No2    0.140220
No3   -0.422600
No4    0.220992
dtype: float64

In [100]:
# the DataFrame class has many convenience methods already built in
df.cumsum()

No1       No2       No3       No4
2015-01-31 -0.424572 -1.611881 -0.821341 -0.775389
2015-02-28 -1.147425 -1.075173 -0.043683 -1.635521
2015-03-31 -2.597467 -1.980677  1.096866 -1.267767
2015-04-30 -4.721325 -2.318552  0.994733  0.815519
2015-05-31 -5.167296 -1.763817 -0.680598  0.674731
2015-06-30 -4.584458 -1.359785 -2.925596  0.300480
2015-07-31 -3.209437  0.193036 -3.120513  1.729192
2015-08-31 -3.414024  0.584066 -4.425082  1.083310
2015-09-30 -5.015572  1.261977 -3.803403  1.988927

In [101]:
type(df.cumsum())

pandas.core.frame.DataFrame

In [98]:
a.cumsum()

array([-0.4245722 , -2.03645321, -2.85779417, -3.63318307, -4.3560356 ,
       -3.81932777, -3.04166995, -3.90180175, -5.35184373, -6.25734705,
       -5.1167983 , -4.74904503, -6.87290343, -7.21077903, -7.31291201,
       -5.22962521, -5.67559578, -5.12086078, -6.79619184, -6.93698063,
       -6.3541427 , -5.9501101 , -8.19510802, -8.56935881, -7.19433793,
       -5.64151718, -5.8364337 , -4.40772157, -4.61230866, -4.22127879,
       -5.52584822, -6.1717303 , -7.773278  , -7.09536758, -6.4736883 ,
       -5.56807093])

In [99]:
type(a.cumsum())

numpy.ndarray

In [97]:
a.cumsum(axis=0)

array([[-0.4245722 , -1.61188101, -0.82134096, -0.77538891],
       [-1.14742472, -1.07517318, -0.04368313, -1.63552071],
       [-2.5974667 , -1.98067651,  1.09686561, -1.26776743],
       [-4.72132511, -2.31855211,  0.99473263,  0.81551937],
       [-5.16729567, -1.76381711, -0.68059843,  0.67473059],
       [-4.58445775, -1.3597845 , -2.92559636,  0.3004798 ],
       [-3.20943687,  0.19303625, -3.12051288,  1.72919193],
       [-3.41402395,  0.58406611, -4.42508231,  1.08330985],
       [-5.01557165,  1.26197653, -3.80340303,  1.98892722]])

In [103]:
#rhere is also a short cut to number of often used statistics for numerical data sets, the describe method

In [106]:

df.describe()

No1       No2       No3       No4
count  9.000000  9.000000  9.000000  9.000000
mean  -0.557286  0.140220 -0.422600  0.220992
std    1.092998  0.944593  1.170280  1.049717
min   -2.123858 -1.611881 -2.244998 -0.860132
25%   -1.450042 -0.337876 -1.304569 -0.645882
50%   -0.445971  0.404033 -0.194917 -0.140789
75%   -0.204587  0.554735  0.621679  0.905617
max    1.375021  1.552821  1.140549  2.083287

In [107]:
#You can also directly apply the majority of numpy universal functions
np.sqrt(df)

No1       No2       No3       No4
2015-01-31       NaN       NaN       NaN       NaN
2015-02-28       NaN  0.732603  0.881849       NaN
2015-03-31       NaN       NaN  1.067965  0.606427
2015-04-30       NaN       NaN       NaN  1.443360
2015-05-31       NaN  0.744805       NaN       NaN
2015-06-30  0.763438  0.635636       NaN       NaN
2015-07-31  1.172613  1.246122       NaN  1.195287
2015-08-31       NaN  0.625324       NaN       NaN
2015-09-30       NaN  0.823353  0.788466  0.951639

In [110]:
#incmomplete data is no problem for pandas
np.sqrt(df).mean()

No1    0.968026
No2    0.801307
No3    0.912760
No4    1.049178
dtype: float64

In [111]:
np.sqrt(df).sum()

No1    1.936051
No2    4.807844
No3    2.738280
No4    4.196713
dtype: float64

In [112]:
Nethier is efficient Plotting

SyntaxError: invalid syntax (<ipython-input-112-f7a78c6356b0>, line 1)

In [ ]:
%Matplotlib inline

In [113]:
#Series Class

In [114]:
#THere is also a dedicated Series class

In [115]:
type(df)

pandas.core.frame.DataFrame

In [116]:
df['No1'].ix[:3]

2015-01-31   -0.424572
2015-02-28   -0.722853
2015-03-31   -1.450042
Freq: M, Name: No1, dtype: float64

In [117]:
type(df['No1'])

pandas.core.series.Series

In [119]:
import matplotlib.pyplot as plt
df['No1'].cumsum.plot(style='r', lw=2.)


AttributeError: 'function' object has no attribute 'plot'

In [120]:
#VEctorized Operations

In [121]:
#Adding two columns

In [122]:
df['No1']+df['No4']

2015-01-31   -1.199961
2015-02-28   -1.582984
2015-03-31   -1.082289
2015-04-30   -0.040572
2015-05-31   -0.586759
2015-06-30    0.208587
2015-07-31    2.803733
2015-08-31   -0.850469
2015-09-30   -0.695930
Freq: M, dtype: float64

In [ ]:
#Multiplication
