# Introduction NumPy Basics

# Array with Pyhon Lists
#Let us set the benchmark wih pure python . First, a vector as list object

In [2]:
v = [0.5, 0.75, 1.0, 1.5, 2.0] #vector of nmbers

In [3]:
#Second a matrixas list of list

In [4]:
m = [v, v, v] # matrix of number

In [5]:
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [6]:
m[1][0]

0.5

In [7]:
#Third a cube as nested list

In [8]:
v1 = [0.5, 1.5]
v2 = [1,  2]
m = [v1,v2]
c=[m,m] #cube of numbers
c

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

In [9]:
c[1][1][0]

1

In [10]:
c[1][1]

[1, 2]

In [11]:
v1[0] ='Python'
m

[['Python', 1.5], [1, 2]]

In [14]:
from copy import deepcopy
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = 3 * [deepcopy(v)]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [16]:
v[0] = 'Python'
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

# NumPy Data Structures

In [17]:
#Regular NmumPy Arays

In [18]:
import numpy as np

In [19]:
a = np.array([0,0.5,1.0,1.5,2.0])
type(a)

numpy.ndarray

In [20]:
a[:2]

array([ 0. ,  0.5])

In [21]:
a.sum()

5.0

In [22]:
sum(a)

5.0

In [23]:
sum([0,0.5,1.0,1.5,2.0])

5.0

In [24]:
a.std()

0.70710678118654757

In [25]:
a.cumsum()

array([ 0. ,  0.5,  1.5,  3. ,  5. ])

#Multipliatin of a list object

In [26]:
l= [0.,0.5,1.5,3.,5.]
2 * l

[0.0, 0.5, 1.5, 3.0, 5.0, 0.0, 0.5, 1.5, 3.0, 5.0]

In [27]:
#In contrast, vectorized operation on the array
2* a

array([ 0.,  1.,  2.,  3.,  4.])

In [28]:
a ** 2

array([ 0.  ,  0.25,  1.  ,  2.25,  4.  ])

# Universal functions for fast omputations

In [29]:
np.sqrt(a)

array([ 0.        ,  0.70710678,  1.        ,  1.22474487,  1.41421356])

In [30]:
np.sqrt(2.5)

1.5811388300841898

In [31]:
import math
math.sqrt(2.5)

1.5811388300841898

In [32]:
math.sqrt(a)

TypeError: only length-1 arrays can be converted to Python scalars

In [33]:
%timeit np.sqrt(2.5)

The slowest run took 34.98 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 518 ns per loop


In [34]:
%timeit math.sqrt(2.5)

10000000 loops, best of 3: 58.4 ns per loop


In [35]:
b = np.array([a, a*2])
b

array([[ 0. ,  0.5,  1. ,  1.5,  2. ],
       [ 0. ,  1. ,  2. ,  3. ,  4. ]])

In [36]:
#data selectio n via indexing

In [37]:
b[0] # first row

array([ 0. ,  0.5,  1. ,  1.5,  2. ])

In [38]:
b[0,2] # third eement from first row

1.0

In [39]:
b.sum()

15.0

In [40]:
b.sum(axis=0) # Column-wise sum

array([ 0. ,  1.5,  3. ,  4.5,  6. ])

In [41]:
b.sum(axis=1) # Row-wise sum

array([  5.,  10.])

In [42]:
#Typical constrction of ndarray objects

In [43]:
 c = np.zeros((2,3,4), dtype='i', order = 'C') # also: np.ones) 2 sub list, 3 rows, 4 columns
c

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [44]:
d = np.ones_like(c, dtype='f16', order = 'C') # also: np.zeros_like
d

array([[[ 1.0,  1.0,  1.0,  1.0],
        [ 1.0,  1.0,  1.0,  1.0],
        [ 1.0,  1.0,  1.0,  1.0]],

       [[ 1.0,  1.0,  1.0,  1.0],
        [ 1.0,  1.0,  1.0,  1.0],
        [ 1.0,  1.0,  1.0,  1.0]]], dtype=float128)

In [45]:
e= np.empty((2,3,4))
e

array([[[  0.00000000e+000,   4.94065646e-324,   9.88131292e-324,
           1.48219694e-323],
        [  1.97626258e-323,   2.47032823e-323,   2.96439388e-323,
           3.45845952e-323],
        [  3.95252517e-323,   4.44659081e-323,   4.94065646e-323,
           5.43472210e-323]],

       [[  5.92878775e-323,   6.42285340e-323,   6.91691904e-323,
           7.41098469e-323],
        [  7.90505033e-323,   8.39911598e-323,   8.89318163e-323,
           9.38724727e-323],
        [  9.88131292e-323,   1.03753786e-322,   1.08694442e-322,
           1.13635099e-322]]])

In [46]:
f = np.empty_like(c)
f

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [47]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [48]:
g = np.linspace(5,10,100)# start, end, number of points
g

array([  5.        ,   5.05050505,   5.1010101 ,   5.15151515,
         5.2020202 ,   5.25252525,   5.3030303 ,   5.35353535,
         5.4040404 ,   5.45454545,   5.50505051,   5.55555556,
         5.60606061,   5.65656566,   5.70707071,   5.75757576,
         5.80808081,   5.85858586,   5.90909091,   5.95959596,
         6.01010101,   6.06060606,   6.11111111,   6.16161616,
         6.21212121,   6.26262626,   6.31313131,   6.36363636,
         6.41414141,   6.46464646,   6.51515152,   6.56565657,
         6.61616162,   6.66666667,   6.71717172,   6.76767677,
         6.81818182,   6.86868687,   6.91919192,   6.96969697,
         7.02020202,   7.07070707,   7.12121212,   7.17171717,
         7.22222222,   7.27272727,   7.32323232,   7.37373737,
         7.42424242,   7.47474747,   7.52525253,   7.57575758,
         7.62626263,   7.67676768,   7.72727273,   7.77777778,
         7.82828283,   7.87878788,   7.92929293,   7.97979798,
         8.03030303,   8.08080808,   8.13131313,   8.18

In [1]:
import numpy as np

In [2]:
# Structure Arrays

In [3]:
dt = np.dtype([('Name', 'S10'),('Age','i4'),('Height','f'),('Chlidren/Pets','i4',2)])
s = np.array([('Smith',45,1.83,(0,1)),
              ('Jones',53,1.72,(2,2))], dtype=dt)
s

array([(b'Smith', 45, 1.8300000429153442, [0, 1]),
       (b'Jones', 53, 1.7200000286102295, [2, 2])], 
      dtype=[('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Chlidren/Pets', '<i4', (2,))])

In [5]:
s['Name']

array([b'Smith', b'Jones'], 
      dtype='|S10')

In [6]:
s['Height'].mean()

1.7750001

In [7]:
s['Age'].std()

4.0

In [121]:
#Vectorization of Code

In [9]:
r = np.random.standard_normal((4,3)) # 4 rows, 3 columns
s = np.random.standard_normal((4,3))

In [10]:
r

array([[-0.26489552,  1.89741841, -0.81186897],
       [ 0.37433993,  1.66502847, -2.21494855],
       [ 0.32092888, -0.70173286,  0.35242248],
       [ 0.97242476,  1.92554886, -0.07263873]])

In [11]:
s

array([[-2.1927174 ,  0.55878396,  0.3969575 ],
       [ 0.25932046,  0.30374364, -0.9956892 ],
       [ 0.57897005, -0.1876422 , -0.44874515],
       [-1.35180647,  0.88259616,  1.02467981]])

In [12]:
r +s #Eleet wise addition

array([[-2.45761292,  2.45620237, -0.41491147],
       [ 0.63366039,  1.96877211, -3.21063775],
       [ 0.89989894, -0.88937505, -0.09632267],
       [-0.37938171,  2.80814502,  0.95204108]])

In [13]:
#Broadcasting
2 * r + 3

array([[ 2.47020896,  6.79483682,  1.37626206],
       [ 3.74867986,  6.33005694, -1.4298971 ],
       [ 3.64185777,  1.59653429,  3.70484496],
       [ 4.94484953,  6.85109772,  2.85472254]])

In [17]:
s = np.random.standard_normal((3))

In [18]:
s

array([ 0.02417423, -0.55408136,  0.15432527])

In [19]:
r

array([[-0.26489552,  1.89741841, -0.81186897],
       [ 0.37433993,  1.66502847, -2.21494855],
       [ 0.32092888, -0.70173286,  0.35242248],
       [ 0.97242476,  1.92554886, -0.07263873]])

In [21]:
r + s

array([[-0.24072129,  1.34333705, -0.6575437 ],
       [ 0.39851417,  1.11094711, -2.06062328],
       [ 0.34510312, -1.25581422,  0.50674775],
       [ 0.996599  ,  1.3714675 ,  0.08168654]])

In [22]:
# caues intentional error
s = np.random.standard_normal((4))
s

array([ 0.11294142,  0.05463036, -3.27859788, -1.65178847])

In [23]:
r+ s

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [25]:
r.T?

In [31]:
np.shape(r)

(4, 3)

In [32]:
np.shape(r.T)

(3, 4)

In [36]:
r.transpose() + s

array([[-0.1519541 ,  0.42897029, -2.957669  , -0.6793637 ],
       [ 2.01035983,  1.71965883, -3.98033074,  0.27376039],
       [-0.69892755, -2.16031819, -2.9261754 , -1.7244272 ]])

In [37]:
r.T + s

array([[-0.1519541 ,  0.42897029, -2.957669  , -0.6793637 ],
       [ 2.01035983,  1.71965883, -3.98033074,  0.27376039],
       [-0.69892755, -2.16031819, -2.9261754 , -1.7244272 ]])

In [38]:
np.shape(r.transpose()) # rows, columns to columns, rows

(3, 4)

In [39]:
np.shape(s)

(4,)

In [ ]:
# A genral Python function

In [40]:
def f(x):
    return 3 * x + 5

In [41]:
f(0.5) # Float number

6.5

In [42]:
f(r) # ndarray variable

array([[  4.20531343,  10.69225523,   2.56439309],
       [  6.12301979,   9.99508541,  -1.64484565],
       [  5.96278665,   2.89480143,   6.05726744],
       [  7.91727429,  10.77664658,   4.78208381]])

In [43]:
# causes intentional error
import math
math.sin(r)

TypeError: only length-1 arrays can be converted to Python scalars

In [44]:
np.sin(r)

array([[-0.26180844,  0.94713153, -0.72557456],
       [ 0.36565825,  0.99556344, -0.79960916],
       [ 0.31544815, -0.64554208,  0.34517241],
       [ 0.826254  ,  0.93773248, -0.07257487]])

In [45]:
np.sin(np.pi)

1.2246467991473532e-16

In [46]:
# Memory Layout

In [48]:
x = np.random.standard_normal((5,100000)) # 5 rows, 100000 columns
y = 2*x + 3 # linear equation y = ax + b
C = np.array((x,y), order='C')
F = np.array((x,y), order='F')
x = 0.0; y =0.0 # memory cleanup

In [49]:
C[:2].round(2)

array([[[-0.29, -0.5 ,  1.84, ...,  0.13, -0.76,  0.51],
        [ 1.86,  0.07, -2.24, ..., -0.03, -1.96, -0.43],
        [ 0.34,  0.62, -0.75, ..., -1.2 , -0.5 , -1.42],
        [-0.81, -0.78, -0.29, ...,  1.4 ,  0.45, -0.3 ],
        [-2.04, -0.43, -1.81, ...,  0.92,  0.  ,  0.23]],

       [[ 2.42,  2.01,  6.68, ...,  3.25,  1.48,  4.02],
        [ 6.73,  3.14, -1.49, ...,  2.94, -0.91,  2.14],
        [ 3.68,  4.23,  1.51, ...,  0.59,  2.01,  0.17],
        [ 1.39,  1.45,  2.42, ...,  5.79,  3.9 ,  2.4 ],
        [-1.07,  2.15, -0.62, ...,  4.84,  3.  ,  3.46]]])

array([[[ -2.90602694e-01,  -4.96786553e-01,   1.83999420e+00, ...,
           1.26283965e-01,  -7.59027122e-01,   5.09314322e-01],
        [  1.86342103e+00,   6.99674937e-02,  -2.24443743e+00, ...,
          -3.18016008e-02,  -1.95747156e+00,  -4.27826365e-01],
        [  3.41082391e-01,   6.15465923e-01,  -7.45910705e-01, ...,
          -1.20371946e+00,  -4.97147894e-01,  -1.41665108e+00],
        [ -8.06060218e-01,  -7.76715890e-01,  -2.91465428e-01, ...,
           1.39676687e+00,   4.51123880e-01,  -2.98683925e-01],
        [ -2.03608483e+00,  -4.25330309e-01,  -1.81101206e+00, ...,
           9.18948840e-01,   9.70481684e-04,   2.29016913e-01]],

       [[  2.41879461e+00,   2.00642689e+00,   6.67998840e+00, ...,
           3.25256793e+00,   1.48194576e+00,   4.01862864e+00],
        [  6.72684206e+00,   3.13993499e+00,  -1.48887487e+00, ...,
           2.93639680e+00,  -9.14943118e-01,   2.14434727e+00],
        [  3.68216478e+00,   4.23093185e+00,   1.50817859e+00, ...,
      

In [51]:
C.shape

(2, 5, 100000)

In [52]:
%timeit C.sum()

1000 loops, best of 3: 351 µs per loop


In [53]:
%timeit F.sum()

1000 loops, best of 3: 346 µs per loop


In [54]:
%timeit C.sum(axis=0) # row

The slowest run took 7.07 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 787 µs per loop


In [55]:
%timeit C.sum(axis=1) # columns  # faster

1000 loops, best of 3: 605 µs per loop


In [56]:
%timeit F.sum(axis=0) # faster

100 loops, best of 3: 5.47 ms per loop


In [58]:
%timeit F.sum(axis=1)

100 loops, best of 3: 16.2 ms per loop


In [64]:
F = 0.0; C= 0.0 # memory clean-up

# Linear Algebra

In [62]:
#Basic Functionality

In [66]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])

In [67]:
a*b

array([ 2,  6, 12])

In [68]:
np.sum(a * b)

20

In [69]:
np.dot(a,b) # dotproduct

20

In [70]:
np.inner(a,b) # inner product

20

In [73]:
o = np.outer (a,b) #outer product # 1st element from 'a' multiply by b, 2nd element from 'a' multiply by b, so on...
o

array([[ 2,  3,  4],
       [ 4,  6,  8],
       [ 6,  9, 12]])

In [75]:
np.linalg.matrix_power(o,3) # matrix power o ** 3

array([[ 800, 1200, 1600],
       [1600, 2400, 3200],
       [2400, 3600, 4800]])

In [76]:
np.dot(o,o)

array([[ 40,  60,  80],
       [ 80, 120, 160],
       [120, 180, 240]])

In [144]:
np.dot(np.dot(o,o),o) # same as before

array([[ 800, 1200, 1600],
       [1600, 2400, 3200],
       [2400, 3600, 4800]])

In [77]:
np.linalg.eigvals(o) # eignvalues)

array([  2.00000000e+01,   3.72357428e-17,   0.00000000e+00])

In [84]:
np.linalg.eig(o) # eignvalues + right eigenvectors

(array([  2.00000000e+01,   3.72357428e-17,   0.00000000e+00]),
 array([[-0.26726124,  0.01384887,  0.14074157],
        [-0.53452248, -0.80323473, -0.82453357],
        [-0.80178373,  0.59550161,  0.54802939]]))

In [115]:
np.linalg.norm?

In [80]:
np.linalg.norm(o, ord = 1) #norm of order 1

24.0

In [81]:
np.linalg.norm(o, ord = 2) #norm of order 2 (deafult)

20.149441679609886

In [82]:
np.linalg.norm(o, axis = 0) #norm of first axis

array([  7.48331477,  11.22497216,  14.96662955])

In [83]:
np.linalg.norm(o, axis = 1) #norm of second axis

array([  5.38516481,  10.77032961,  16.15549442])

In [87]:
np.arange(4)

array([0, 1, 2, 3])

In [88]:
m= np.arange(4).reshape((2,2))
m

array([[0, 1],
       [2, 3]])

In [89]:
np.linalg.det(m) # determinant

-2.0

In [90]:
i = np.linalg.inv(m) # inverse
i

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [94]:
np.dot(m,i) #Identity matrix

array([[ 1.,  0.],
       [ 0.,  1.]])

In [95]:
np.eye?

In [92]:
np.eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [96]:
np.dot(m,i) == np.eye(2)

array([[ True,  True],
       [ True,  True]], dtype=bool)

# Sloving Systems of Linear Equations

In [98]:
import numpy as np

#we are going to solve equations of type:
 $                                               a.x=b$
consider the system of linear equations which fits the above type:
                                                       $             a1.x1  +a1 **2.x1=b1$
                                                       $             a2.x2  +a2 **2.x2=b2$

In [ ]:
#first, matrix a

In [106]:
a = np.array([[3,1],[1,2]])
a

array([[3, 1],
       [1, 2]])

In [ ]:
#second vector b

In [107]:
b = np.array([9,8])
b

array([9, 8])

In [104]:
#Third the solution

In [105]:
x=np.linalg.solve(a,b)
x

array([ 2.,  3.])

In [112]:
a = np.array([[3,1,1],[1,2,1], [1,1,2]])
b = np.array([10.5, 8.25, 7.75])

In [113]:
x = np.linalg.solve(a,b)
x

array([ 2.21428571,  2.17857143,  1.67857143])

In [114]:
np.dot(a,x) #checking

array([ 10.5 ,   8.25,   7.75])

In [161]:
import random
random.gauss(0,1)

-0.6737572665402916